{% set version = "3.3.1" %}

package:
  name: nvtop
  version: {{ version }}

source:
  url: https://github.com/Syllo/nvtop/archive/refs/tags/{{ version }}.tar.gz
  sha256: 8318aff973e0850bea4b9d7d313c513206cdc9b8387e8441681e84ac2bc0e980

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - ncurses
    - libdrm  # [linux]
    - libsystemd  # [linux]

test:
  commands:
    - test -f $PREFIX/bin/nvtop
    - nvtop --help

about:
  home: https://github.com/Syllo/nvtop
  summary: Neat Videocard TOP
  description: |
    A (h)top like task monitor for GPUs and accelerators. It can handle
    multiple GPUs and print information about them in a htop-familiar way.
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - hmaarrfk
    - matthiasdiener
