{% set version = "3.1.0" %}

package:
  name: nvtop
  version: {{ version }}

source:
  url: https://github.com/Syllo/nvtop/archive/refs/tags/{{ version }}.tar.gz
  sha256: 9481c45c136163574f1f16d87789859430bc90a1dc62f181b269b5edd92f01f3
  patches:
    # https://github.com/Syllo/nvtop/pull/272
    - remove_kcmp.patch

build:
  number: 1
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
  host:
    - ncurses
    - libdrm  # [linux]
    - libsystemd  # [linux]

test:
  commands:
    - test -f $PREFIX/bin/nvtop
    - nvtop --help  # [build_platform == target_platform]

about:
  home: https://github.com/Syllo/nvtop
  summary: Neat Videocard TOP
  description: |
    A (h)top like task monitor for AMD and NVIDIA GPUs. It can handle multiple
    GPUs and print information about them in a htop familiar way.
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - hmaarrfk
    - matthiasdiener
