{% set version = "3.0.1" %}

package:
  name: nvtop
  version: {{ version }}

source:
  url: https://github.com/Syllo/nvtop/archive/refs/tags/{{ version }}.tar.gz
  sha256: f61ecbe3a30a216706c16fc177d3b840e7d7deccf87b048d59f95f230d591a53
  patches:
    # https://github.com/Syllo/nvtop/pull/154
    # - 154-link_rt.patch
    - amd_syscall_definitions.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - sysroot_linux-64 2.17  # [linux64]
    - cmake
    - make
  host:
    - ncurses
    - libdrm
    - libsystemd

test:
  commands:
    - nvtop --help

about:
  home: https://github.com/Syllo/nvtop
  summary: Neat Videocard TOP
  description: |
    A (h)top like task monitor for AMD and NVIDIA GPUs. It can handle multiple
    GPUs and print information about them in a htop familiar way.
  license: GPL-3.0-only
  license_family: GPL
  license_file: COPYING

extra:
  recipe-maintainers:
    - hmaarrfk
    - matthiasdiener
